export const APPEND_LIKE = 'APPEND_LIKE';
export const CHANGE_ACTIVE_PATIENTS = 'CHANGE_ACTIVE_PATIENTS';
export const CHANGE_ACTIVE_PATIENT_ID = 'CHANGE_PATIENT_SONG_ID';
export const CHANGE_ACTIVE_USER_ID = 'CHANGE_ACTIVE_USER_ID';
export const CHANGE_CURRENT_TIME = 'CHANGE_CURRENT_TIME';
export const CHANGE_MODAL = 'CHANGE_MODAL';
export const CHANGE_PATH = 'CHANGE_PATH';

export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';

export const RECEIVE_ACCESS_TOKEN = 'RECEIVE_ACCESS_TOKEN';
export const RECEIVE_AUTHED_FOLLOWINGS = 'RECEIVE_AUTHED_FOLLOWINGS';
export const RECEIVE_AUTHED_PLAYLISTS = 'RECEIVE_AUTHED_PLAYLISTS';
export const RECEIVE_AUTHED_USER = 'RECEIVE_AUTHED_USER';
export const RECEIVE_LIKES = 'RECEIVE_LIKES';
export const RECEIVE_PATIENT = 'RECEIVE_PATIENT';
export const RECEIVE_PATIENT_CONDITIONS = 'RECEIVE_PATIENT_CONDITIONS';
export const RECEIVE_PATIENTS = 'RECEIVE_PATIENTS';
export const RECEIVE_NEW_STREAM_SONGS = 'RECEIVE_NEW_STREAM_SONGS';
export const RECEIVE_USER = 'RECEIVE_USER';
export const RECEIVE_USER_FOLLOWINGS = 'RECEIVE_USER_FOLLOWINGS';
export const RECEIVE_USER_PROFILES = 'RECEIVE_USER_PROFILES';
export const REMOVE_UNLIKED_SONGS = 'REMOVE_UNLIKED_SONGS';
export const RESET_AUTHED = 'RESET_AUTHED';
export const REQUEST_PATIENT = 'REQUEST_PATIENT';
export const REQUEST_PATIENTS = 'REQUEST_PATIENTS';
export const REQUEST_USER = 'REQUEST_USER';
