export MasterPage from './MasterPage'
export LoginPage from './LoginPage'
export RegistrationPage from './RegistrationPage'
export ProfilePage from './ProfilePage'
export PatientPage from './PatientPage'
export PatientCampaignPage from './PatientCampaignPage'
export DonatePage from './DonatePage'
export ConfirmationPage from './ConfirmationPage'
